packageExtensions:
  "@parcel/workers@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
  "@parcel/fs@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
  "@parcel/cache@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
  "@parcel/package-manager@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"